### ISSUE TITLE
No library found for imobiledevice, plist and usbmuxd

### ISSUE THREAD

**Issue by VictorLeweke** [Schlaubischlump/LocationSpoofer#5]
For the targets imobiledevice, plist and usbmuxd, I get the error "While building for iOS, no library for this platform was found in '/Users/user/Library/Developer/Xcode/DerivedData/Spoof-gocdkddfnvevivasvqhjcuxpqzrv/SourcePackages/artifacts/locationspoofer/imobiledevice.xcframework'."

**Comment by Schlaubischlump** [comment]
It won't work on iOS. iOS does not have a usbmuxd deamon.
